# Generated by Django 5.0 on 2024-02-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='cpwd',
        ),
        migrations.AlterField(
            model_name='register',
            name='phno',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterModelTable(
            name='register',
            table='register_table',
        ),
    ]
