# Generated by Django 5.0 on 2024-02-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
