# Generated by Django 5.0 on 2024-02-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_packages_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
